---
remote_theme: pmarsceill/just-the-docs
title: MIT RACECAR-MN Course
nav_order: 7
---

description: Welcome to the 2020 RACECAR-MN course!

baseurl: "/RacecarWebsite"
url: "https://matthewcalligaro.github.io"

search_enabled: true
heading_anchors: true

aux_links:
  "RACECAR-MN on github":
    - "//github.com/MatthewCalligaro/RacecarWebsite"
    
footer_content: "Copyright &copy; 2020 Harvey Mudd College. Distributed by an <a href=\"https://github.com/MatthewCalligaro/RacecarWebsite/blob/master/LICENSE\">MIT license.</a>"

